# Generated by Django 4.0.6 on 2022-07-13 03:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, unique=True)),
                ('username', models.CharField(default='unknown_user', max_length=100)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('dob_month', models.CharField(default='', max_length=100)),
                ('dob_day', models.CharField(default='', max_length=100)),
                ('dob_year', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('zipcode', models.CharField(default='', max_length=5)),
                ('url', models.URLField()),
                ('about', models.CharField(default='', max_length=256)),
                ('biSitter', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='catty.userinfo'), max_length=100)),
                ('headline', models.CharField(default='', max_length=100)),
                ('service', models.CharField(default='onboarding', max_length=10)),
                ('rate', models.IntegerField()),
                ('note', models.CharField(default='', max_length=100)),
                ('disable', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=b'I01\n', max_length=20), size=None), size=None)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='catty.userinfo')),
            ],
        ),
    ]
