# Generated by Django 4.0.6 on 2022-07-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='zipcode',
            field=models.CharField(default='', max_length=5),
        ),
    ]
