# Generated by Django 4.0.6 on 2022-07-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='cell',
            field=models.CharField(default='', max_length=10),
        ),
    ]
