# Generated by Django 4.0.6 on 2022-07-13 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='email',
        ),
    ]
