# Generated by Django 4.0.6 on 2022-07-16 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catty', '0002_service_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='zipcode',
        ),
    ]
