# Generated by Django 4.0.6 on 2022-07-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catty', '0003_alter_service_disable_alter_service_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='note',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
