# Generated by Django 4.0.6 on 2022-07-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catty', '0005_service_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='about',
            field=models.CharField(default='', max_length=256),
        ),
    ]
