# Generated by Django 4.0.6 on 2022-07-19 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catty', '0006_service_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writen_by', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=500)),
                ('content', models.CharField(default='', max_length=500)),
                ('rating', models.IntegerField()),
                ('writen_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catty.service')),
            ],
        ),
    ]
