# Generated by Django 4.0.6 on 2022-07-19 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catty', '0007_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='writen_by',
            new_name='written_by',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='writen_to',
            new_name='written_to',
        ),
    ]
